### ISSUE TITLE
Dont run CI on README edits

### ISSUE THREAD

**Issue by rido-min** [Azure/iot-plugandplay-models-tools#114]
https://github.com/Azure/iot-plugandplay-models-tools/blob/b1a831099e6589c31ad34dd6257a0b1a984835cf/.github/workflows/merge.yml#L6

**Comment by digimaun** [comment]
Resolved in a [prior iteration](https://github.com/Azure/iot-plugandplay-models-tools/blob/dev/.github/workflows/merge.yml#L8).
