### ISSUE TITLE
Validate --strict in expanded form

### ISSUE THREAD

**Issue by rido-min** [Azure/iot-plugandplay-models-tools#125]
dmr-client validate accepts a JSON array (as the parser accepts the array as well).

However EnsureSubDtmiNamespace --strict check should fail though the current implementation won't support an array.

**Comment by digimaun** [comment]
This is now the behavior using `dmr-client/1.0.0-beta.1`.

**Example**

No error validating the expanded (array of models) TemperatureController model.
![image](https://user-images.githubusercontent.com/28658112/99613893-42c25a80-29cd-11eb-9bf6-7a03e6f024e3.png)

Now using `--strict`, well provide a friendly error.

![image](https://user-images.githubusercontent.com/28658112/99613993-72716280-29cd-11eb-97b9-016430b3cce1.png)

**Comment by rido-min** [comment]
I was expecting that validating a file with the expanded form will use the interfaces in the array to resolve dependencies.

**Comment by digimaun** [comment]
That should be the case already. Is there some behavior that leads you to believe its not? When you use a file that contains an array, each array model is extracted separately into the collection which is passed to the parser.

**Comment by digimaun** [comment]
You can verify this by running `dmr-client validate` against an exported model and seeing there are no resolution fetches occurring - 
![image](https://user-images.githubusercontent.com/28658112/99710783-d93a5e80-2a55-11eb-97a9-ee0454503eda.png)
