### ISSUE TITLE
Can't find Microsoft.Azure.DigitalTwins.Parser

### ISSUE THREAD

**Issue by maurert** [Azure/iot-plugandplay-models-tools#138]
The Nuget package is available here: https://www.nuget.org/packages/Microsoft.Azure.DigitalTwins.Parser/
But I can't find the source code. The Project site link on Nuget leads to a 404 on Github.

**Comment by maurert** [comment]
Am I correct to assume that the DTDL parser is not Open Source?

**Comment by rido-min** [comment]
Hi @mauret 

Yes, your assumption is correct. 

May I ask you what would you do if it was open source? Do you have any issue with DTDL or the parser? Any information you provide will help us to prioritize this decission.

**Comment by maurert** [comment]
Currently I would like to extend the dtdl model with other content types besides telemetry, properties and commands. 

In the future other extensions could be nessesary to better fit the solution I'm working with.

**Comment by rido-min** [comment]
Hi @maurert 

You can find the new DTDLParser (in preview) here https://github.com/digitaltwinconsortium/DTDLParser

Once it's GA we will adopted in this repo
