### ISSUE TITLE
Checks should warn on non dtmi changes

### ISSUE THREAD

**Issue by rido-min** [Azure/iot-plugandplay-models-tools#140]
![image](https://user-images.githubusercontent.com/14916339/101819238-c9a0b980-3ad9-11eb-930c-6e16a377b689.png)

**Comment by digimaun** [comment]
The 1.0.0 model validation action will show a warning for non dtmi file changes 

For example https://github.com/Azure/iot-plugandplay-models/pull/446/files
![image](https://user-images.githubusercontent.com/28658112/164118396-4ee93185-4dde-4f4e-82c6-b53470937557.png)
