### ISSUE TITLE
Doc updates

### ISSUE THREAD

**Issue by rido-min** [Azure/iot-plugandplay-models-tools#2]
- [x] Publishing Guidelines
- [x] Resolution sample
- [x] Update existing pnp docs.ms.com

   "As an external or internal customer, I have the documentation I need to use and interact
    with the DMR."

**Comment by houmanp** [comment]
Here are the URLs that need updating to reflect the removal of the CLI namespace and changes to model repo:
https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/pnp/model?view=azure-cli-latest#ext_azure_iot_az_iot_pnp_model_show

https://docs.microsoft.com/en-us/azure/iot-pnp/howto-use-iot-pnp-cli

https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-model-repository

https://docs.microsoft.com/en-us/azure/iot-pnp/overview-iot-plug-and-play

**Comment by rido-min** [comment]
@houmanp are these changes covered on the PR I mentioned above? if not, can you comment on the docs PR?
