### ISSUE TITLE
GitHub Validation Worfklows

### ISSUE THREAD

**Issue by iluican** [Azure/iot-plugandplay-models-tools#33]
As per this spec:

https://github.com/Azure/device-models-tools/wiki/Validation-Pipeline

**Comment by rido-min** [comment]
adding related items

#75

**Comment by montgomp** [comment]
This is available in test via this [PR](https://github.com/Azure/iot-plugandplay-models-test/pull/18). When comfortable with testing complete, we can move to prod.
