### ISSUE TITLE
Block PRs with changed models

### ISSUE THREAD

**Issue by rido-min** [Azure/iot-plugandplay-models-tools#90]
A PR with a modified model should be rejected, eg: https://github.com/Azure/iot-plugandplay-models-test/pull/9/checks

**Comment by montgomp** [comment]
Adding steps to log and fail for all dtdl documents that are listed in `steps.files.outputs.renamed`, `steps.files.ouptuts.removed`, and `steps.outputs.files.modified`. As well as adding a new workflow to fail for items that aren't in the `/dtmi/` folder.
